### ISSUE TITLE
Migration from AMS

### ISSUE THREAD

**Issue by lucashungaro** [yosiat/panko_serializer#137]
Hi! Sorry about opening an issue, I tried to find other forms of contact but it appears the links to the Slack community are broken.

I have a large project using AMS that should benefit a lot from more efficient serializers. Is Panko a drop-in replacement for AMS at this point? Is there a migration guide of any sort? I'm trying to gauge/estimate the work to migrate and that would greatly help me.

If I had a simple list of what works and what doesn't I could just go the "install Panko, replace AMS references, replace non-compatible methods, and run the specs" route. :)

Thank you!

**Comment by yosiat** [comment]
Hi @lucashungaro 

The migration is not a drop-in replacement, actually in a repo I have at work we use both AMS and Panko and do serializer-by-serializer migration, since there are breaking changes - the use of `Panko::Response` and other-features.

**Comment by lucashungaro** [comment]
Hi @yosiat, thanks for the response!

So that would be the ideal migration process? Install them side by side and slowly migrate? It there any simple way to know which features from AMS this gem doesn't cover?

**Comment by yosiat** [comment]
Hey @lucashungaro, sorry for the late response 🙏

At my company, we have AMS 0.9 installed alongside Panko. Since we heavily rely on serializers and have many of them, our migration process is as follows:

- **For new code**: If it's a root serializer, it must be written using Panko. For non-root serializers, it's highly preferred to create new ones using Panko and use them.
- **Existing serializers**: We are migrating them slowly, one by one. We started with high-traffic endpoints, where using Panko provides the most value. For low-traffic endpoints, we are migrating them gradually.

There isn't a feature support matrix between Panko and AMS 0.9. Panko was inspired by AMS 0.9, so the interface/API is roughly 70% similar, but the implementation is different.
