### ISSUE TITLE
Model methods

### ISSUE THREAD

**Issue by SnowyLeopard** [yosiat/panko_serializer#30]
Hello,

I'm trying to add a model method as a value/attribute to the serializer, like it is possible in AMS.

I have a method defined on the model:

```
class Product < ApplicationRecord
  ...
  def display_name
    ...
  end
end
```

In AMS I was able to add this method to the attributes list in the serializer and this would work.
I can make it work in panko by calling the method within a method in the serializer:
```
class ProductSerializer < ApplicationSerializer
  attributes :id, :display_name

  def display_name
    object.display_name
  end
end
```

Is this something you would be able to and willing to add? Would be much appreciated!
Loving the serializer so far!

Regards,
Snowy Leopard

**Comment by yosiat** [comment]
Hi @SnowyLeopard !

It's possible in AMS since behind the scenes AMS calls `send` on an object for attribute name to fetch it's value, and panko for performance reasons doesn't (see - https://yosiat.github.io/panko_serializer/design-choices.html#type-casting)
So method attributes will work as you said for now.

- Yosi

**Comment by SnowyLeopard** [comment]
Hey @yosiat,

Thanks for the answer, makes sense!

Closing the issue!

Regards,
SnowyLeopard
