### ISSUE TITLE
Custom methods on an ActiveRecord model object don't get serialized

### ISSUE THREAD

**Issue by dkulchenko** [yosiat/panko_serializer#34]
I defined a few custom methods on my AR model, but when I add them as attributes to the serialization, it ignores them. I worked around it for now by adding a no-op method in the serializer:

```ruby
attributes :photos
```

doesn't put anything in the final JSON, but:

```ruby
attributes :photos
def photos
  object.photos
end
```

does.

**Comment by yosiat** [comment]
Hi @dkulchenko !

The reason `attributes :photos` just work in other serialization libraries is because behind the scene they call `object.photos` in order to read it's value.
While Panko, don't do this - we peek into the ActiveRecord internals to read the value.

In my codebase, instead of no-op method I use `delegate :photos, to :object`

Hopefully this clears things for you

**Comment by dkulchenko** [comment]
Ah - makes sense, thank you!
